### ISSUE TITLE
1.44 version doesn't resolve

### ISSUE THREAD

**Issue by taralrathodcondenast** [BranchMetrics/ios-branch-sdk-spm#10]
Hi,
Via SPM, the version 1.44 doesn't resolve correctly and fails with error "Dependencies could not be resolved because no versions of 'ios-branch-sdk-spm' match the requirement 1.44 and root depends on 'ios-branch-sdk-spm' 1.44"
Seems like that is tagged wrong and doesn't contain 3 parts like how normal versions are tagged. I think this should get resolved if it gets tagged correctly to "1.44.0" instead of "1.44". 
Could you please address this?

**Comment by echo-branch** [comment]
Thanks for the heads up! Updated, let me know if you still have issue.
