### ISSUE TITLE
Tag for 1.45.1 is 1.451.0

### ISSUE THREAD

**Issue by simondelphia** [BranchMetrics/ios-branch-sdk-spm#12]
FYI the tag for the [latest release](https://github.com/BranchMetrics/ios-branch-sdk-spm/releases/tag/1.451) is incorrectly coming up as `1.451.0` instead of `1.45.1`

<img width="556" alt="image" src="https://user-images.githubusercontent.com/69437320/205755143-f06158ad-5c7d-465d-90d2-a9bba84a925e.png">

<img width="607" alt="image" src="https://user-images.githubusercontent.com/69437320/205755320-c39a0c6e-2f49-47a6-9552-eb31776d73d5.png">

**Comment by jf-branch** [comment]
Hi @simondelphia This should be fixed now.

**Comment by simondelphia** [comment]
Xcode "Update to Latest Package Versions" is still producing 1.451.0 for me, but maybe it's because of caching.

**Comment by xmollv** [comment]
> Xcode "Update to Latest Package Versions" is still producing 1.451.0 for me, but maybe it's because of caching.

Same, still showing as 1.451.0 for me 😬

**Comment by jf-branch** [comment]
Hi @simondelphia @xmollv, could you try now?

**Comment by simondelphia** [comment]
I actually just manually edited the version inside the package.resolved file to `1.45.1` and that built fine (commit hash matched). Haven't tried it otherwise.

**Comment by jf-branch** [comment]
Awesome great to hear this is resolved!
