### ISSUE TITLE
Not able to test univarsal links when added via SPM

### ISSUE THREAD

**Issue by nikitrivedii** [BranchMetrics/ios-branch-sdk-spm#16]
### Describe the bug

I have integrated Branch from pod to SPM.

And my unit test case started to fail.. Not sure what is going wrong..

here is my code snippet

```
fun test{
 let result = appDelegate.application(
            UIApplication.shared,
            continue: NSUserActivity(
                activityType: NSUserActivityTypeBrowsingWeb
            )
        ) { (_) in }
        XCTAssertFalse(result)
}
```

and method implementation for universal link is

```
func application(
		_ application: UIApplication,
		continue userActivity: NSUserActivity,
		restorationHandler: @escaping ([UIUserActivityRestoring]?) -> Void
	) -> Bool {

		// Tab Selection code

		return Branch.getInstance().continue(userActivity)
	}
```

### Steps to reproduce

1. Add Unit test for Universal Link
2. Test it
3. Test case fails

### Expected behavior

Test case should not fail

### SDK Version

2.1.0 - Next minor

### XCode Version

14.1

### Device

iPhone 14 Pro

### OS

Ventura 13.1

### Additional Information/Context

I do not have real device, so couldn't check if universal links are broken due to this or not. I can only check my test cases..

**Comment by echo-branch** [comment]
@nikitrivedii 
I think you need to set a URL on the activity.
