### ISSUE TITLE
Apple search ads?

### ISSUE THREAD

**Issue by mmdock** [BranchMetrics/ios-branch-sdk-spm#19]
### Describe the bug

I believe this may be a documentation error / conflicting documentation

I am going through setup documention again while updating from 1.45.2 to 2.2.0 (while also switching from Cocoapods to SPM at the same time for integration)

I am encountering the following issue:
https://help.branch.io/developers-hub/docs/ios-full-reference#apple-search-ads

This document says i need to implement:
- You must add the iAd.framework to your project to enable Apple Search Ad checking.
- and `Branch.getInstance().delayInitToCheckForSearchAds`

Now I had `Branch.getInstance().delayInitToCheckForSearchAds` this as part of my setup for 1.45.2, however, i am now getting xcode error: 

`Value of type 'Branch' has no member 'delayInitToCheckForSearchAds'`

Finally, in the instructions for SPM integration, there doesn't appear to be any mention of iAd.framework integration like the document above describes.  

### Steps to reproduce

1. Be integrated with 1.45.2 via Cocoapods
2. migrate to SPM integration and update to 2.2.0

### Expected behavior

Clearer instructions or sdk notes about the function being deprecated or something

### SDK Version

2.20

### XCode Version

14.2 (14C18)

### Device

NA

### OS

NA

**Comment by echo-branch** [comment]
@mmdock Sorry about that, we had intended to remove that documentation about the old Apple Search Ads. I'll inform docs that it's still up.

**Comment by echo-branch** [comment]
Yes. Apple deprecated the old version and it doesn't return anything. The new version uses a token and s2s integration, so no delay is necessary with it.
