### ISSUE TITLE
Conversion Value Mappings API doesn't return any values

### ISSUE THREAD

**Issue by navasiloy** [BranchMetrics/ios-branch-sdk-spm#21]
### Describe the bug

https://api2.branch.io/v2/partners/a_facebook/conversion-value-mappings?app_id=1664503999

### Steps to reproduce

1. Hit a GET request and you don't get any values or
2. Use it in Ads Manager does not import any value
<img width="1385" alt="Screenshot 2023-11-15 at 18 22 30" src="https://github.com/BranchMetrics/ios-branch-sdk-spm/assets/3064708/92146d42-f2e3-432b-b6fc-5fdfe89ead6a">
<img width="1389" alt="Screenshot 2023-11-15 at 18 22 41" src="https://github.com/BranchMetrics/ios-branch-sdk-spm/assets/3064708/7ed8188e-96bf-436c-9c9f-bc37f04d0cfc">

### Expected behavior

Configuration should be able to be imported into 3rd party 

### SDK Version

api2.branch.io

### XCode Version

15.0.1

### Device

iPhone 11

### OS

16.5.1

**Comment by echo-branch** [comment]
@navasiloy 
Please file an support ticket. This repo is for SDK side issues, sounds like you're working on another thing entirely.
https://help.branch.io/using-branch/page/submit-a-ticket
