### ISSUE TITLE
Deferred link returned only in unspecified condition

### ISSUE THREAD

**Issue by jendaz** [BranchMetrics/ios-branch-sdk-spm#26]
### Describe the bug

We've just implemented deferred link using Branch SDK.
It worked well when installed from TestFlight or Xcode. But then I just realized that the link is not returned when my phone is on mobile data and is working on my home WiFi.
It works on hot-spot and not via WiFi for my colleague.

We are sometimes getting no branch link `[“+is_first_session”: 1, “+clicked_branch_link”: 0]`

### Steps to reproduce

1. delete app
2. click link
3. install app (AppStore/TestFlight/Xcode)
4. observe if the link goes through

repeate few times with different network setup

### Expected behavior

The app should open deferred link always after fresh installation

### SDK Version

3.1.0

### XCode Version

15.2

### Device

various

### OS

various

### Additional Information/Context

I would expect that you are getting some kind of fingerprint of the device through the link also based on the network setup. But it is maybe remembered from the first clicking on the link. So I would assume that the fingerprint should renew when user taps on the link.

Is there something we can improve in the integration or branch link setup? Would implementing NativeLink help with that? Or is is a bug in getting the fingerprint?

We are currently not sure if it is working for all users who installs the app using to the Branch link.

**Comment by echo-branch** [comment]
@jendaz 
Apple's privacy rules forbids building a device fingerprint, so we do not build or use fingerprints on Apple platforms. This means we cannot confidently tell users apart when many recent similar devices are on the same IP address and will err on the safe side and not return data.

We recommend using https://help.branch.io/faq/docs/nativelink-deferred-deep-linking, which is a pasteboard based deterministic deferred deeplink.
