### ISSUE TITLE
App Crashes on BNCUserAgentCollector collectUserAgentWithCompletion method

### ISSUE THREAD

**Issue by Vaisakhk1990** [BranchMetrics/ios-branch-sdk-spm#33]
### Describe the bug

Hi We are using Branch SDK 1.41.0 After initialising the SDK We are getting crash  attached the Screenshot of the log.
We tried to upgrade to 3.4.1. But the same issue persist.

We are trying in Xcode 15.4
                           iOS      17.5.1
                           iPhone 12 and 11 pro max

### Steps to reproduce

1. Initialise the SDK from AppDelegate
2. Then try to run on Real device

### Expected behavior

Should not crash

### SDK Version

1.41.0 and 3.4.1

### XCode Version

15.4

### Device

iPhone 12 and 11 pro max

### OS

17.5.1

**Comment by thatswiftdev** [comment]
[
![Screenshot 2024-08-07 at 10 30 44](https://github.com/user-attachments/assets/2e0d0a54-67b3-47d0-aa4d-d5b1bbd688bf)
](url)

This issue still persist
