### ISSUE TITLE
[BNCServerInterface genericHTTPRequest:retryNumber:callback:retryHandler:] Giving up on request with HTTP status code 400

### ISSUE THREAD

**Issue by avinashamanjha251** [BranchMetrics/ios-branch-sdk-spm#34]
### Describe the bug

Getting 400 while creating short link using BranchLinkProperties and BranchUniversalObject.

![WhatsApp Image 2024-06-13 at 13 53 18](https://github.com/BranchMetrics/ios-branch-sdk-spm/assets/27722634/aa6a89c4-18ac-4ffe-8f6c-109eff6dd482)

### Steps to reproduce

1. Initialise the SDK from AppDelegate
2. Try to create short link 

### Expected behavior

Expecting shorten link

### SDK Version

3.4.4

### XCode Version

15.4

### Device

iPhone 13

### OS

17.3.1

**Comment by avinashamanjha251** [comment]
guys any update?

**Comment by farzi-insan** [comment]
I'm facing same.
team please help me on the same

**Comment by avinashamanjha251** [comment]
Guys, I added some code in BranchShortUrlRequest. Please take a look at it, as I am getting the following response for the shortened URL.

{
    code = 400;
    message = "Link alias conflict: refer.livwell.asia/avinazwopg";
}

<img width="744" alt="Screenshot 2024-06-26 at 6 02 49 PM" src="https://github.com/BranchMetrics/ios-branch-sdk-spm/assets/27722634/e5b149ea-c6a8-432b-b881-2b3520ef2186">
