### ISSUE TITLE
React Native App crash with with ios SDK version 3.4.4

### ISSUE THREAD

**Issue by amosaxe** [BranchMetrics/ios-branch-sdk-spm#37]
### Describe the bug

Hi, 

Suddenly since today our ios app with io.branch.sdk.version:3.4.4 is crashing. Please find the stack trace below

> Fatal Exception: NSInvalidArgumentException
> 0  CoreFoundation                 0x83f20 __exceptionPreprocess
> 1  libobjc.A.dylib                0x172b8 objc_exception_throw
> 2  CoreFoundation                 0x15e6c -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]
> 3  CoreFoundation                 0x15a88 +[NSDictionary dictionaryWithObjects:forKeys:count:]
> 4  Froker                         0x552728 __84-[RNBranch generateShortUrl:withLinkProperties:withControlParams:resolver:rejecter:]_block_invoke + 567 (RNBranch.m:567)
> 5  Froker                         0xbe260 -[BranchShortUrlRequest processResponse:error:] + 96 (BranchShortUrlRequest.m:96)
> 6  Froker                         0xabe98 __40-[Branch processRequest:response:error:]_block_invoke + 1766 (Branch.m:1766)
> 7  libdispatch.dylib              0x3dd4 _dispatch_client_callout
> 8  libdispatch.dylib              0x1339c _dispatch_async_and_wait_invoke
> 9  libdispatch.dylib              0x3dd4 _dispatch_client_callout
> 10 libdispatch.dylib              0x125a4 _dispatch_main_queue_drain
> 11 libdispatch.dylib              0x121b8 _dispatch_main_queue_callback_4CF
> 12 CoreFoundation                 0x56710 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
> 13 CoreFoundation                 0x53914 __CFRunLoopRun
> 14 CoreFoundation                 0x52cd8 CFRunLoopRunSpecific
> 15 GraphicsServices               0x11a8 GSEventRunModal
> 16 UIKitCore                      0x40aae8 -[UIApplication _run]
> 17 UIKitCore                      0x4bed98 UIApplicationMain
> 18 Froker                         0x84e8 main + 9 (main.m:9)
> 19 ???                            0x1b44bb154 (Missing)

I am posting this issue here as there is no issue section in the react native repo. 

### Steps to reproduce

1. use react native branch sdk ("react-native-branch": "^6.2.2")
2. open the app
3. crash occurs

### Expected behavior

For the crash to not occur

### SDK Version

3.4.4

### XCode Version

15.2

### Device

iphone 14 pro max, iphone 13 pro

### OS

17.6.1

**Comment by amosaxe** [comment]
I tried updating to the latest version of react native sdk to 6.3.0 which uses  iOS SDK 3.6.3, still the same issue

**Comment by amosaxe** [comment]
Hi team, please reply, every user is being effected by this

**Comment by amosaxe** [comment]
@NidhiDixit09 @rkim-branch hi guys, sorry to disturb but this is a sev0 for us, if any one can help

**Comment by rkim-branch** [comment]
I will take a look at it soon.

**Comment by ahmednawar** [comment]
@amosaxe we think that this was caused by a backend change that we just reverted. Can you please re-test and let us know if you are still experiencing the crashes?

**Comment by amosaxe** [comment]
Hi @ahmednawar , yes it is working as expected now, thanks for this.

**Comment by amosaxe** [comment]
@ahmednawar thanks for helping ASAP, closing the issue.
