### ISSUE TITLE
Lots of warnings about umbrellla headers not including headers

### ISSUE THREAD

**Issue by simondelphia** [BranchMetrics/ios-branch-sdk-spm#8]
<img width="452" alt="image" src="https://user-images.githubusercontent.com/69437320/197265470-2ab2de46-6f29-4fb4-8be9-cc2dd0d0f28c.png">

e.g. 

> Umbrella header for module 'Branch' does not include header 'BNCPasteboard.'

Using 1.44.0

Hadn't noticed this before when we were on 1.43.2, but maybe I just missed it.

* Similar issue on the other repo: https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/issues/1153

Xcode 14.0
macOS 12.6 (21G115)

Here's the full list
> ios-branch-sdk-spm/Branch-SDK/Branch.h:1855:1: warning build: Umbrella header for module 'Branch' does not include header 'BNCTuneUtility.h'
> ios-branch-sdk-spm/Branch-SDK/Branch.h:1855:1: warning build: Umbrella header for module 'Branch' does not include header 'BNCKeyChain.h'
> ios-branch-sdk-spm/Branch-SDK/Branch.h:1855:1: warning build: Umbrella header for module 'Branch' does not include header 'BNCTelephony.h'
> ios-branch-sdk-spm/Branch-SDK/Branch.h:1855:1: warning build: Umbrella header for module 'Branch' does not include header 'BranchCPIDRequest.h'
> ios-branch-sdk-spm/Branch-SDK/Branch.h:1855:1: warning build: Umbrella header for module 'Branch' does not include header 'BNCAppleReceipt.h'
> ios-branch-sdk-spm/Branch-SDK/Branch.h:1855:1: warning build: Umbrella header for module 'Branch' does not include header 'BNCPasteboard.h'
> ios-branch-sdk-spm/Branch-SDK/Branch.h:1855:1: warning build: Umbrella header for module 'Branch' does not include header 'BranchContentPathProperties.h'
> ios-branch-sdk-spm/Branch-SDK/Branch.h:1855:1: warning build: Umbrella header for module 'Branch' does not include header 'BNCSKAdNetwork.h'
> ios-branch-sdk-spm/Branch-SDK/Branch.h:1855:1: warning build: Umbrella header for module 'Branch' does not include header 'BNCJSONUtility.h'
> ios-branch-sdk-spm/Branch-SDK/Branch.h:1855:1: warning build: Umbrella header for module 'Branch' does not include header 'BNCAppleAdClient.h'
> ios-branch-sdk-spm/Branch-SDK/Branch.h:1855:1: warning build: Umbrella header for module 'Branch' does not include header 'BNCAppGroupsData.h'
> ios-branch-sdk-spm/Branch-SDK/Branch.h:1855:1: warning build: Umbrella header for module 'Branch' does not include header 'BNCFieldDefines.h'
> ios-branch-sdk-spm/Branch-SDK/Branch.h:1855:1: warning build: Umbrella header for module 'Branch' does not include header 'BNCSpotlightService.h'
> ios-branch-sdk-spm/Branch-SDK/Branch.h:1855:1: warning build: Umbrella header for module 'Branch' does not include header 'BNCCallbackMap.h'
> ios-branch-sdk-spm/Branch-SDK/Branch.h:1855:1: warning build: Umbrella header for module 'Branch' does not include header 'BranchShortUrlSyncRequest.h'
> ios-branch-sdk-spm/Branch-SDK/Branch.h:1855:1: warning build: Umbrella header for module 'Branch' does not include header 'BNCQRCodeCache.h'
> ios-branch-sdk-spm/Branch-SDK/Branch.h:1855:1: warning build: Umbrella header for module 'Branch' does not include header 'BranchOpenRequest.h'
> ios-branch-sdk-spm/Branch-SDK/Branch.h:1855:1: warning build: Umbrella header for module 'Branch' does not include header 'BranchShortUrlRequest.h'
> ios-branch-sdk-spm/Branch-SDK/Branch.h:1855:1: warning build: Umbrella header for module 'Branch' does not include header 'BranchLogoutRequest.h'
> ios-branch-sdk-spm/Branch-SDK/Branch.h:1855:1: warning build: Umbrella header for module 'Branch' does not include header 'BNCApplication.h'
> ios-branch-sdk-spm/Branch-SDK/Branch.h:1855:1: warning build: Umbrella header for module 'Branch' does not include header 'NSMutableDictionary+Branch.h'
> ios-branch-sdk-spm/Branch-SDK/Branch.h:1855:1: warning build: Umbrella header for module 'Branch' does not include header 'BNCDeviceSystem.h'
> ios-branch-sdk-spm/Branch-SDK/Branch.h:1855:1: warning build: Umbrella header for module 'Branch' does not include header 'BranchPasteControl.h'
> ios-branch-sdk-spm/Branch-SDK/Branch.h:1855:1: warning build: Umbrella header for module 'Branch' does not include header 'BNCUserAgentCollector.h'
> ios-branch-sdk-spm/Branch-SDK/Branch.h:1855:1: warning build: Umbrella header for module 'Branch' does not include header 'BNCFacebookAppLinks.h'
> ios-branch-sdk-spm/Branch-SDK/Branch.h:1855:1: warning build: Umbrella header for module 'Branch' does not include header 'BNCEncodingUtils.h'
> ios-branch-sdk-spm/Branch-SDK/Branch.h:1855:1: warning build: Umbrella header for module 'Branch' does not include header 'BNCURLFilter.h'
> ios-branch-sdk-spm/Branch-SDK/Branch.h:1855:1: warning build: Umbrella header for module 'Branch' does not include header 'BNCNetworkInterface.h'
> ios-branch-sdk-spm/Branch-SDK/Branch.h:1855:1: warning build: Umbrella header for module 'Branch' does not include header 'BranchUserCompletedActionRequest.h'
> ios-branch-sdk-spm/Branch-SDK/Branch.h:1855:1: warning build: Umbrella header for module 'Branch' does not include header 'BranchRegisterViewRequest.h'
> ios-branch-sdk-spm/Branch-SDK/Branch.h:1855:1: warning build: Umbrella header for module 'Branch' does not include header 'BNCThreads.h'
> ios-branch-sdk-spm/Branch-SDK/Branch.h:1855:1: warning build: Umbrella header for module 'Branch' does not include header 'BNCSystemObserver.h'
> ios-branch-sdk-spm/Branch-SDK/Branch.h:1855:1: warning build: Umbrella header for module 'Branch' does not include header 'BranchSetIdentityRequest.h'
> ios-branch-sdk-spm/Branch-SDK/Branch.h:1855:1: warning build: Umbrella header for module 'Branch' does not include header 'NSString+Branch.h'
> ios-branch-sdk-spm/Branch-SDK/Branch.h:1855:1: warning build: Umbrella header for module 'Branch' does not include header 'BranchInstallRequest.h'
> ios-branch-sdk-spm/Branch-SDK/Branch.h:1855:1: warning build: Umbrella header for module 'Branch' does not include header 'Branch+Validator.h'
> ios-branch-sdk-spm/Branch-SDK/Branch.h:1855:1: warning build: Umbrella header for module 'Branch' does not include header 'BNCDeepLinkViewControllerInstance.h'
> ios-branch-sdk-spm/Branch-SDK/Branch.h:1855:1: warning build: Umbrella header for module 'Branch' does not include header 'BNCContentDiscoveryManager.h'
> ios-branch-sdk-spm/Branch-SDK/Branch.h:1855:1: warning build: Umbrella header for module 'Branch' does not include header 'BNCDeviceInfo.h'
> ios-branch-sdk-spm/Branch-SDK/Branch.h:1855:1: warning build: Umbrella header for module 'Branch' does not include header 'BNCAppleSearchAds.h'
> ios-branch-sdk-spm/Branch-SDK/Branch.h:1855:1: warning build: Umbrella header for module 'Branch' does not include header 'BranchContentDiscoverer.h'
> ios-branch-sdk-spm/Branch-SDK/Branch.h:1855:1: warning build: Umbrella header for module 'Branch' does not include header 'BNCLocale.h'
> ios-branch-sdk-spm/Branch-SDK/Branch.h:1855:1: warning build: Umbrella header for module 'Branch' does not include header 'BranchSpotlightUrlRequest.h'
> ios-branch-sdk-spm/Branch-SDK/Branch.h:1855:1: warning build: Umbrella header for module 'Branch' does not include header 'BranchContentDiscoveryManifest.h'
> ios-branch-sdk-spm/Branch-SDK/Branch.h:1855:1: warning build: Umbrella header for module 'Branch' does not include header 'BranchCloseRequest.h'
> ios-branch-sdk-spm/Branch-SDK/Branch.h:1855:1: warning build: Umbrella header for module 'Branch' does not include header 'BNCPartnerParameters.h'
> ios-branch-sdk-spm/Branch-SDK/Branch.h:1855:1: warning build: Umbrella header for module 'Branch' does not include header 'BranchJsonConfig.h'
> ios-branch-sdk-spm/Branch-SDK/Branch.h:1855:1: warning build: Umbrella header for module 'Branch' does not include header 'BranchLATDRequest.h'
> ios-branch-sdk-spm/Branch-SDK/Branch.h:1855:1: warning build: Umbrella header for module 'Branch' does not include header 'BNCCrashlyticsWrapper.h'
> ios-branch-sdk-spm/Branch-SDK/Branch.h:1855:1: warning build: Umbrella header for module 'Branch' does not include header 'BNCNetworkService.h'
> ios-branch-sdk-spm/Branch-SDK/Branch.h:1855:1: warning build: Umbrella header for module 'Branch' does not include header 'BNCReachability.h'

**Comment by nsingh-branch** [comment]
Hi, thank you for bringing this to our attention. I just to confirm this is something on the SDK's end. Could you try cleaning your project, deleting your derived data, and restarting Xcode to see if these warnings persist?

**Comment by simondelphia** [comment]
They are not showing at the moment. I didn't have to delete derived data but since I've posted this I've definitely done the other two.

**Comment by nsingh-branch** [comment]
@simondelphia That great to hear and it sounds like the issue is fixed, so i'll go ahead and close out the issue. Let us know if this comes backs.

**Comment by simondelphia** [comment]
They're back now

**Comment by xmollv** [comment]
@nsingh-branch They're also showing up for me. I've just moved Branch from Cocoapods to SPM and this is what I get now:

<img width="688" alt="Screenshot 2022-11-16 at 17 19 50" src="https://user-images.githubusercontent.com/8229382/202235374-c7d474eb-083d-42b9-9ddc-cd8a50d1f315.png">

**Comment by xmollv** [comment]
Digging around looks like it's going to be fixed soon: → https://github.com/BranchMetrics/ios-branch-deep-linking-attribution/issues/1101#issuecomment-1314132725

**Comment by arthurofbabylon** [comment]
Not fixed. Totally ruining my zero issue rule.

**Comment by simondelphia** [comment]
Still getting it quite often as well
